### ISSUE TITLE
Usage with nav controller and tab bar?

### ISSUE THREAD

**Issue by alexcoplan** [tonisalae/TSMiniWebBrowser#11]
Hi there,

What would you suggest for usage with a tab bar and a nav controller - will we need to create a new mode? At the moment I'm using the default (navigation mode?) and it works well, except that the action sheet is not shown from the tab bar, but the bottom of the screen and so the cancel button can't be selected.

My first idea was to not create a new mode, but add a config option called "useTabBar" (or similar), and that would simply tell it to present the actionsheet from the tab bar, whilst maintaining the current mode behaviour (e.g. navigation).

Alternatively, we could create a new mode TSMiniWebBrowserModeNavigationTabBar or something..

What do you think?

**Comment by alexcoplan** [comment]
Fixed in my latest commit [here](https://github.com/tonisalae/TSMiniWebBrowser/pull/10).

**Comment by tonisalae** [comment]
This issue with the tabbar makes the app crash in my tests. Did you tested it on various devices and iOS versions?

**Comment by tonisalae** [comment]
I have changed this condition:

else if (mode == TSMiniWebBrowserModeNavigation && [self.navigationController respondsToSelector:@selector(tabBarController)])

to this:

else if (mode == TSMiniWebBrowserModeNavigation && self.navigationController.tabBarController != nil)

This appears to work just fine in my tests. Does it make sense for you?

**Comment by alexcoplan** [comment]
Yep that makes sense - thank you.
