### ISSUE TITLE
Browser crashes if pushed on navigation controller and then 'back' is pressed during page load

### ISSUE THREAD

**Issue by suneets** [tonisalae/TSMiniWebBrowser#3]
I use TSMiniWebBrowser with a navigation controller-- I found that if I push the view onto the navigation controller, but then press "back" very quickly in the middle of the initial page load request-- the app crashes, with a message sent to a deallocated instance of TSMiniWebBrowser.

I found a quick fix for this, simply add:

-(void)dealloc
{
    [webView setDelegate:nil];
}

I can submit a request through Github..

**Comment by tonisalae** [comment]
Merged!

Thank you very much!
