### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by Bodacious** [tonisalae/TSMiniWebBrowser#6]
Hey - this library is great!

Would be really cool if I could use it with [Cocoapods](http://cocoapods.org/) though. Would you mind submitting it to them?

**Comment by tonisalae** [comment]
I didn't know cocoapods. I'll take a look and consider to submit TSMiniWebBrowser to them :)

Thanks!

**Comment by Bodacious** [comment]
Thanks :-)

**Comment by btaylor** [comment]
I'll have this done in a few minutes, as I need it for some of our internal projects.

In the future, it would be awesome if TSMiniWebBrowser had tags for releases.  If this was in place, I wouldn't have to pick an arbitrary commit id and arbitrary version numbers for the spec files.

**Comment by btaylor** [comment]
Done.  Enjoy!

http://cocoapods.org/?q=tsminiwebbrowser
